name: "Create Link"

on:
  issues:
    types: [opened]

jobs:
  NewWord:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.body, '喂!我要建立短網址啦!')
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      
    - name: 建立短址
      env:
        REPOSITORY: ${{ github.repository }}
        EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
        EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
      run: |
            echo ${{ secrets.GITHUB_TOKEN }} > token.txt
            gh auth login --with-token < token.txt
            echo supersecret > token.txt
            rm -r token.txt
            gh issue comment https://github.com/charlie-moomoo/textboard/issues/${{ github.event.issue.number }} --body "$(curl -s https://ssur.cc/api.php?appkey=nZ9ZzSa4LZ4o&format=text&longurl=${{ github.event.issue.title }})"
            gh issue close https://github.com/charlie-moomoo/textboard/issues/${{ github.event.issue.number }}
