name: "New Word"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '增加文字|')
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      
    - name: 增加文字
      env:
        REPOSITORY: ${{ github.repository }}
        EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
        EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
      run: |
            sh word.sh ${{ github.event.issue.title }} ${{ github.event.issue.user.login }}
      
